### ISSUE TITLE
Make the async function a public / replacable object of the core library

### ISSUE THREAD

**Issue by PonteIneptique** [alpheios-project/morphlib#2]
If we want the library to be truly reusable, I think the function that is used internally to retrieve data (quite possibly an ajax function) should be made **a public core member of the library**. It would be then **used internally by controllers** in the library. Not so much for it to be reused by developers but mostly for it to be rewritten or replaced by function available in other framework : 
- in angularJs, it could be interesting to replace the function `morphlib.async` by a component to cache resource, 
- in node context it could be interesting to reuse morphlib (and I am not sure this is the same request that is used)

**Comment by balmas** [comment]
I've added this to the requirements. @PonteIneptique is this the example we should refer to:

https://github.com/Capitains/Sparrow/blob/master/src/modules/utils.js#L284
https://github.com/Capitains/Sparrow/blob/master/src/modules/utils.js#L38-L121

**Comment by balmas** [comment]
from @PonteIneptique, basically avoid 
`a.function() { $.ajax()... }`
but rather `a.function() { a.ajax() };`
