### ISSUE TITLE
Improve event registration

### ISSUE THREAD

**Issue by hcayless** [alpheios-project/morphlib#28]
Testing with a DLL text, and finding that it works (yay!) but the popup gets triggered a bunch of times. This must be because https://github.com/alpheios-project/morphlib/blob/master/modules/morphlib.js#L102 sets the doubleclick handler on every element inside the body—these texts have 6 or 7 of those before you hit any text, so the popup gets triggered that many times. Suggest making it configurable, or only match text-containing elements.

**Comment by elijahjcooke** [comment]
I was able to just change a setting in the jquery event handler to only fire once per click. one the preferences UI is ready you will also be able to select which elements you want to fire the event also.
