### ISSUE TITLE
HTTPS Issues

### ISSUE THREAD

**Issue by hcayless** [alpheios-project/morphlib#33]
Discovered this trying it out on GitHub Pages (which is all-HTTPS). Because the API lookups are HTTP URLs, they don't work unless you make them HTTPS, which you can do for Perseids URLs (e.g. https://github.com/alpheios-project/morphlib/blob/master/modules/preferences.js#L53), but which doesn't work for any of the alpheios.net URLs, meaning full dictionary lookups don't work either unless you mess with the browser's security settings.

**Comment by balmas** [comment]
Yes. Will be fixing this fully  next week by deploying Alpheios services under https.

**Comment by balmas** [comment]
should be fixed now. URLs for perseids and alpheios all changed to https. Let me know if you have any further problems with this!
